[package]
name = "WindowAware"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_UI_Accessibility",   
    "Win32_System_Threading",       # OpenProcess
    "Win32_System_ProcessStatus",   # GetModuleBaseName
    "Win32_UI_WindowsAndMessaging",
    "Win32_Security",               # 权限相关常量
] }